title: Yusuke Mori's website
description: Yusuke Mori (forest1988)'s User Page of 'GitHub Pages'.
google_analytics: 
show_downloads: false
# theme: jekyll-theme-cayman
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

gems:
  - jekyll-mentions
  - bulma-clean-theme
